# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Airflow + MLflow Docker Compose Configuration
# Uses CeleryExecutor, Redis, PostgreSQL
# Deploys Airflow components and a dedicated MLflow Tracking Server
---
version: '3.8' # Added compose file version

# Common configuration reusable across Airflow services
x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.9.2-python3.9}
  environment:
    &airflow-common-env
    # --- ADDED: Prevent Python from writing .pyc files ---
    PYTHONDONTWRITEBYTECODE: "1"

    # --- Airflow Core Settings ---
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: '' # NOTE: Set a fixed key for production consistency
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true' # Default behavior
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'

    # --- BASE Python Dependencies (Scheduler, Webserver, Triggerer, Worker Base) ---
    # Lean list: Core providers, common clients
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-apache-airflow-providers-postgres apache-airflow-providers-redis apache-airflow-providers-celery psycopg2-binary redis celery>=5.2.0 beautifulsoup4 PyPDF2 pinecone python-dotenv mlflow google-cloud-storage dvc[gs] requests==2.31.0 gunicorn}

    # --- Common Environment Variables (Available to all Airflow tasks) ---
    # These are loaded from .env file mounted into the container or host environment
    OPENAI_API_KEY: ${OPENAI_API_KEY}
    LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
    LANGSMITH_PROJECT: ${LANGSMITH_PROJECT}
    LANGSMITH_TRACING: ${LANGSMITH_TRACING}
    PINECONE_API_KEY: ${PINECONE_API_KEY}
    PINECONE_INDEX_NAME: ${PINECONE_INDEX_NAME} # Made available to tasks if needed
    PINECONE_ENVIRONMENT: ${PINECONE_ENVIRONMENT}
    HEVY_API_KEY: ${HEVY_API_KEY}
    MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://mlflow-server:5000} # Tasks use this to find MLflow server
    MLFLOW_ARTIFACT_ROOT: ${MLFLOW_ARTIFACT_ROOT:-gs://ragllm-454718-mlflow-artifacts} # GCS bucket for artifacts

  volumes:
    # Mount project root to /opt/airflow/app for access to src/, etc.
    - ${AIRFLOW_PROJ_DIR:-.}:/opt/airflow/app:rw # Ensure read-write if needed
    # Mount specific Airflow directories
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags:ro # Read-only recommended for DAGs
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs:rw # Needs read-write
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins:ro # Read-only recommended
    - ${AIRFLOW_PROJ_DIR:-.}/.env:/opt/airflow/app/.env:ro # Mount .env read-only

  # user: "${AIRFLOW_UID:-50000}:0" # Keep commented unless fixing permissions

  # --- ADDED: Explicit Network Attachment ---
  networks:
    - airflow_net # All airflow-common services will attach to this network

  depends_on: # Common dependencies for most Airflow services
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    container_name: personaltrainerai-postgres-1 # Optional: explicit naming
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow # Single DB for Airflow & MLflow metadata (dev only)
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks: # Attach to the defined network
      - airflow_net

  redis:
    image: redis:7.2-bookworm
    container_name: personaltrainerai-redis-1 # Optional: explicit naming
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    networks: # Attach to the defined network
      - airflow_net

  mlflow-server:
    image: python:3.9-slim
    container_name: personaltrainerai-mlflow-server-1
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql+psycopg2://airflow:airflow@postgres/airflow
      MLFLOW_ARTIFACT_ROOT: ${MLFLOW_ARTIFACT_ROOT:-gs://ragllm-454718-mlflow-artifacts}
      # Note: GCS access relies on VM service account credentials
    volumes: [] # No host volumes needed
    command: >
      bash -c "echo 'Ensuring pip...' && python3 -m ensurepip --upgrade && \
               echo 'Installing MLflow deps...' && pip install --no-cache-dir mlflow psycopg2-binary google-cloud-storage && \
               echo 'Starting MLflow server...' && \
               mlflow server \
                --host 0.0.0.0 \
                --port 5000 \
                --backend-store-uri $$MLFLOW_BACKEND_STORE_URI \
                --default-artifact-root $$MLFLOW_ARTIFACT_ROOT"
    ports:
      - "5001:5000" # Expose on host 5001 -> container 5000
    restart: always
    networks: # Attach to the defined network
      - airflow_net
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    <<: *airflow-common
    container_name: personaltrainerai-airflow-webserver-1 # Optional: explicit naming
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s; timeout: 10s; retries: 5; start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init: { condition: service_completed_successfully }
      mlflow-server: { condition: service_started } # Wait for mlflow to start

  airflow-scheduler:
    <<: *airflow-common
    container_name: personaltrainerai-airflow-scheduler-1 # Optional: explicit naming
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8973/health"] # Correct port for Airflow 2.9+
      interval: 30s; timeout: 10s; retries: 5; start_period: 60s # Increased start period
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init: { condition: service_completed_successfully }
      mlflow-server: { condition: service_started }

  airflow-worker:
    <<: *airflow-common
    container_name: personaltrainerai-airflow-worker-1 # Optional: explicit naming
    command: celery worker
    healthcheck:
      test: ["CMD-SHELL", 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"']
      interval: 30s; timeout: 10s; retries: 5; start_period: 60s # Increased start period for dep install
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
      # --- OVERRIDE: Install BASE + WORKER-SPECIFIC dependencies ---
      _PIP_ADDITIONAL_REQUIREMENTS: "${_PIP_ADDITIONAL_REQUIREMENTS} langchain langchain-openai langchain_community langchain_huggingface openai ragas deepseek langsmith scikit-learn numpy pandas tqdm matplotlib sentence-transformers torch transformers datasets" # Append heavy libs
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init: { condition: service_completed_successfully }
      mlflow-server: { condition: service_started }

  airflow-triggerer:
    <<: *airflow-common
    container_name: personaltrainerai-airflow-triggerer-1 # Optional: explicit naming
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s; timeout: 10s; retries: 5; start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init: { condition: service_completed_successfully }
      mlflow-server: { condition: service_started }

  airflow-init:
    <<: *airflow-common
    container_name: personaltrainerai-airflow-init-1 # Optional: explicit naming
    entrypoint: /bin/bash
    command: # More explicit init steps
      - -c
      - |
        set -e
        echo "Airflow Init: Starting initialization..."
        # Ensure directories exist (both for checks and runtime)
        mkdir -p /sources/logs /sources/dags /sources/plugins /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins
        # Permissions - Ensure logs dir is writable
        chmod -R 777 /sources/logs || echo "WARN: Failed chmod /sources/logs"
        # Optional: Chown if running as non-root (AIRFLOW_UID set)
        if [[ -n "${AIRFLOW_UID}" && "${AIRFLOW_UID}" != "0" ]]; then
          echo "Changing ownership for AIRFLOW_UID=${AIRFLOW_UID}..."
          chown -R "${AIRFLOW_UID}:0" /sources/logs /sources/dags /sources/plugins || echo "WARN: Failed chown /sources"
        fi
        # Run DB migration
        echo "Running Airflow DB migrate..."
        airflow db migrate
        # Create Admin User (handle potential existing user error)
        echo "Creating Airflow Admin User (user: ${_AIRFLOW_WWW_USER_USERNAME:-admin})..."
        airflow users create \
            --username "${_AIRFLOW_WWW_USER_USERNAME:-admin}" \
            --password "${_AIRFLOW_WWW_USER_PASSWORD:-admin}" \
            --firstname "${_AIRFLOW_WWW_USER_FIRSTNAME:-Default}" \
            --lastname "${_AIRFLOW_WWW_USER_LASTNAME:-User}" \
            --role "${_AIRFLOW_WWW_USER_ROLE:-Admin}" \
            --email "${_AIRFLOW_WWW_USER_EMAIL:-admin@example.com}" || \
        echo "Admin user likely already exists."
        echo "Airflow Init: Initialization complete."
    environment:
      <<: *airflow-common-env
      # Override requirements - only need db driver for init
      _PIP_ADDITIONAL_REQUIREMENTS: 'psycopg2-binary'
      # Explicitly set desired admin user details here or via .env
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_WWW_USER_USERNAME:-Vinyas}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_WWW_USER_PASSWORD:-Vinyas}
      # _AIRFLOW_WWW_USER_FIRSTNAME: # Optional
      # _AIRFLOW_WWW_USER_LASTNAME: # Optional
      # _AIRFLOW_WWW_USER_ROLE: # Optional (defaults to Admin)
      # _AIRFLOW_WWW_USER_EMAIL: # Optional
    user: "0:0" # Run init as root for permissions/setup
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/sources:rw # Need rw for potential checks/chown
    # No network needed if it only interacts with DB via localhost mapped service name? Add if needed.
    # networks:
    #   - airflow_net
    depends_on: # Only needs DB to be ready
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy } # Although not directly used, ensures broker is ready for later components

  airflow-cli:
    <<: *airflow-common
    container_name: personaltrainerai-airflow-cli-1 # Optional: explicit naming
    profiles: ["debug", "cli"] # Add cli profile
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    command: ["bash"] # Keep running
    tty: true

  flower:
    <<: *airflow-common
    container_name: personaltrainerai-flower-1 # Optional: explicit naming
    command: celery flower
    profiles: ["flower"]
    ports:
      - "5555:5555"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 30s; timeout: 10s; retries: 5; start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init: { condition: service_completed_successfully }
      mlflow-server: { condition: service_started }


# --- Define the network ---
networks:
  airflow_net: # Define the network name
    driver: bridge # Use standard bridge driver

volumes:
  postgres-db-volume: # Define the named volume for Postgres data persistence