"""add_exercise_template_table

Revision ID: 7690ad45de58
Revises: 92f2818e4d14
Create Date: 2025-03-29 19:32:28.459926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7690ad45de58'
down_revision: Union[str, None] = '92f2818e4d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('primary_muscle_group', sa.String(length=50), nullable=False),
    sa.Column('secondary_muscle_groups', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_templates')
    # ### end Alembic commands ###
