"""change_exercise_id_to_str

Revision ID: e5ea20596c44
Revises: 7690ad45de58
Create Date: 2025-03-29 19:43:36.842310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ea20596c44'
down_revision: Union[str, None] = '7690ad45de58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise_templates', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise_templates', 'id',
               existing_type=sa.String(length=50),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
