name: Evaluate Model Quality

permissions:
  id-token: write
  contents: read

# runs bi‑weekly at 07:00 UTC
on:
  schedule:
    - cron: '0 7 */14 * *'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCS_BUCKET:  ${{ secrets.GCS_BUCKET }}
  GAR_LOCATION: ${{ secrets.CLOUD_RUN_REGION }}
  REGION: ${{ secrets.CLOUD_RUN_REGION }}

jobs:
  evaluate-and-upload:
    name: Run evaluation & upload metrics
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write secrets to .env for evaluation
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}" >> .env
          echo "LANGSMITH_API=${{ secrets.LANGSMITH_API }}" >> .env
          echo "LANGSMITH_TRACING=${{ secrets.LANGSMITH_TRACING }}" >> .env
          echo "LANGSMITH_PROJECT=${{ secrets.LANGSMITH_PROJECT }}" >> .env

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Run evaluation script
        id: eval
        run: |
          python src/chatbot/agent_eval/eval.py > eval_output.json
      #     accuracy=$(jq '.accuracy | tonumber' eval_output.json)
      #     echo "Model accuracy: $accuracy"
      #     echo "accuracy=$accuracy" >> $GITHUB_OUTPUT

      - name: Upload metrics to GCS
        run: |
          TS=$(date -u +"%Y%m%dT%H%M%SZ")
          gsutil cp eval_output.json "gs://${{ env.GCS_BUCKET }}/model_metrics/eval_${TS}.json"

      - name: Parse accuracy
        run: |
          # read the JSON you just generated
          accuracy=$(jq -r '.accuracy' eval_output.json)
          echo "Model accuracy: $accuracy"
          # export for the if‑condition below
          echo "accuracy=$accuracy" >> $GITHUB_OUTPUT
    
      - name: Notify via Email if Accuracy < 0.95
        if: ${{ steps.eval.outputs.accuracy < 0.95 }}
        env:
          EMAIL_SENDER:   ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECIEVER }}
        run: |
          python - << 'EOF'
          import os, json, smtplib
          from email.mime.text import MIMEText
          from email.mime.multipart import MIMEMultipart
    
          # load credentials
          sender   = os.environ["EMAIL_SENDER"]
          password = os.environ["EMAIL_PASSWORD"]
          receiver = os.environ["EMAIL_RECEIVER"].strip()

          if not receiver:
            raise ValueError("EMAIL_RECEIVER environment variable is empty")

          # load your eval output
          with open("eval_output.json") as f:
              data = json.load(f)
          accuracy = data.get("accuracy", 0.0)
    
          # compose message
          subject = "🚨 Model Accuracy Alert"
          body = f"""Hi Team,
    
          The latest model evaluation shows accuracy dropped below 99%.
    
          Current Accuracy: {accuracy:.2%}
    
          Please investigate and retrain if necessary.
    
          Regards,
          GitHub Actions Bot
          """
    
          msg = MIMEMultipart()
          msg["From"]    = sender
          msg["To"]      = receiver
          msg["Subject"] = subject
          msg.attach(MIMEText(body, "plain"))

          print(f"Sending email from {sender} to {receiver}")

          # send via Gmail SMTP
          with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            # Use sendmail with explicit parameters instead of send_message
            server.sendmail(sender, receiver, msg.as_string())
          EOF
